kafka:
  bootstrapService: localhost:9092
  producer:
    topic: test-topic
    producerGroupId: test-group
    blockTimeMs: 2000 # default 60000
    requestTimeout: 500
    batchSize: 16384 # default 16384
    lingerMs: 10 # default 0
    maxRequestSize: 1048576 # default 1024 * 1024
    bufferMemory: 33554432 # default 32 * 1024 * 1024 (33554432)
    retries: 0 # default 0
