spring:
  kafka:
    consumer:
      groupId: 1
      bootstrapServers: localhost:9095
    producer:
      bootstrapServers: localhost:9095
      acks: all
      properties:
        request.timeout.ms: 500
    listener:
      type: BATCH
      ackMode: BATCH
      concurrency: 1
      pollTimeout: 500
      maxPollRecords: 500
      enableAutoCommit: true
      autoCommitInterval: 500
      autoOffsetReset: latest

kafka:
  consumer:
    topic: 456
  producer:
    topic: 123
