apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller   # имя контроллера репликаций
spec:
  replicas: 3   # количество реплик пода
  template:
    metadata:
      labels:
        app: my-web-service-label   # метка по которой контроллер репликаций отслеживает поды
    spec:
      containers:
        - name: my-web-service
          image: plekhanov/my_service_image
          ports:
            - containerPort: 8080